### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by cam900** [gm-archive/gmapi#3]
COPYING file says LGPL 2.1, but LICENSE contains LGPL 3.0 copy.
It's dual license or something else?

**Comment by cher-nov** [comment]
> COPYING file says LGPL 2.1, but LICENSE contains LGPL 3.0 copy.

This is the way it was in the original repository. I just renamed `LICENSE` to `COPYING` and `lgpl-3.0.txt` to `LICENSE` (see c5be594feea6849993fbc1f0a8c28c21267f35ee) to make GitHub auto-detect the repository's license properly.

Also, COPYING allows not only LGPL 2.1, but any newer LGPL as well (thus including 3.0 and even possible future versions):
https://github.com/gm-archive/gmapi/blob/c5be594feea6849993fbc1f0a8c28c21267f35ee/COPYING#L7

> It's dual license or something else?

To be honest, I don't know the correct term. Forward licensing?
